services:

  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/import

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mongo-seed:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./data:/data/import
    entrypoint: >
      bash -c "
        sleep 5 &&
        mongoimport --host mongo --db itexto --collection performance --file /data/import/performance.json --jsonArray --username root --password example --authenticationDatabase admin &&
        mongoimport --host mongo --db itexto --collection posts --file /data/import/posts.json --jsonArray --username root --password example --authenticationDatabase admin
      "