version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/import
    command: >
      bash -c "
        mongod --bind_ip_all &
        sleep 5 &&
        mongoimport --db=itexto --collection=post --file=/data/import/posts.json --jsonArray &&
        mongoimport --db=itexto --collection=performance --file=/data/import/performance.json --jsonArray
      "