services:

  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
    volumes:
      - ./data:/data/import

  mongo-seed:
    image: mongo
    depends_on:
      - mongo
    volumes:
      - ./data:/data/import
    entrypoint: >
      bash -c "
        sleep 5 &&
        mongoimport --db=itexto --collection=performance --file=/data/import/performance.json --jsonArray &&
        mongoimport --db=itexto --collection=posts --file=/data/import/posts.json --jsonArray &&
        mongoimport --db=itexto --collection=sites --file=/data/import/sites.json --jsonArray 
      "